apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service-app
  labels:
    app: account-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service-app
  template:
    metadata:
      labels:
        app: account-service-app
    spec:
      containers:
        - name: account-service-app
          image: angular.azurecr.io/account-service:v3
          imagePullPolicy: Always
          ports:
            - containerPort: 8092

---
apiVersion: v1
kind: Service
metadata:
  name: account-service-svc
spec:
  ports:
    - targetPort: 8092
      port: 80
  selector:
    app: customer-service-app