apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular
  labels:
    app: angular
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular
  template:
    metadata:
      labels:
        app: angular
    spec:
      containers:
        - name: angular
          image: angular.azurecr.io/angular-service:v3
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: angular
spec:
  type: ClusterIP
  selector:
    app: angular
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
---
apiVersion: v1
kind: Service
metadata:
  name: angular-external
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: http
  selector:
    app: angular